# Generated by Django 5.2.8 on 2026-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
